# Default configuration for ChatAgent
# Values can be overridden by environment variables prefixed with CHATAGENT_

db = "~/.chatagent/chatagent.sqlite3"
workspace = "~/sandbox/chatagent/projects"
model_default = "gemini-1.5-flash"
llm_provider = "echo"
host = "0.0.0.0"
port = 8080
log_level = "INFO"
log_pii = false
