name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - name: Checkout
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v5
      - name: Set up Python
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Build package
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          python -m pip install build
          python -m build backend
